### ISSUE TITLE
Option to add ONLY guide lines

### ISSUE THREAD

**Issue by alpe12** [mattsemar/dsp-bulldozer#16]
It would be great if this was possible.
Thanks.

**Comment by mattsemar** [comment]
So would you want the land under the lines flattened/paved? I think this is possible, but not without leveling that ground first. If you don't play in FullCheat mode that can be kind of costly in terms of foundation (and to a lesser extent) soilpile

**Comment by alpe12** [comment]
> So would you want the land under the lines flattened/paved?

Yes, and painted with the configured collor.

> that can be kind of costly in terms of foundation (and to a lesser extent) soilpile

That's ok. It's less than adding foundation to the entire planet. :)

**Comment by Flerndip** [comment]
I signed up just to leave this same suggestion.  Depressing to see that it's been sitting here since February.  It would be helpful if Bulldozer mod added the option to pave only the colored sections that mark the boundaries between topological bands.  Just like it does now but don't fill in the rest of the pavement.  Just pave the sections that you're currently coloring.

This would allow the player to easily section off the useful bands and leave natural sections instead of just turning every planet into an identical parking lot.

**Comment by mattsemar** [comment]
Ok, I added support for this in version 1.1.7. There's a new setting in the config window you can use, "GuideLinesOnly". 

It was actually harder to do than it might seem, but it should mostly work now with a couple caveats:

1. Soil pile is not currently consumed. I do want to fix this, but the way the game calculates how much is needed is kind of hard for me to replicate.
2. I noticed a few spots where the guidelines will be missing a bit of paint. When this happens you should be able to fly to that spot, place foundation and then bulldoze again.

**Comment by Flerndip** [comment]
Thanks for this feature addition!
